---
- name: install wp-cli
  get_url:
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: /usr/local/bin/wp
    mode: 0755

- name: check wp installed
  stat:
    path: "{{ wp_path }}/wp-config.php"
  register: wp_installed

- name: create wp directory
  file: path="{{ wp_path }}" state=directory owner=apache group=apache mode=0755
  ignore_errors: yes
  when: not wp_installed.stat.exists

- name: Download wp core
  shell: /usr/local/bin/wp core download --locale=ja --path="{{ wp_path }}" --force
  become: yes
  become_user: apache
  ignore_errors: yes
  when: not wp_installed.stat.exists

- name: Generate wp config
  shell: /usr/local/bin/wp core config --dbname="{{ wp_dbname }}" --dbuser="{{ wp_dbuser }}" --dbpass="{{ wp_dbpass }}" --dbhost="localhost" --path="{{ wp_path }}"
  become: yes
  become_user: apache
  ignore_errors: yes
  when: not wp_installed.stat.exists

- name: Install wp
  shell: /usr/local/bin/wp core install --url="http://{{ ansible_host }}/wp/" --title="{{ wp_title }}" --admin_user="{{ wp_admin_user }}" --admin_password="{{ wp_admin_pass }}" --admin_email="{{ wp_admin_email }}" --path="{{ wp_path }}"
  become: yes
  become_user: apache
  ignore_errors: yes
  when: not wp_installed.stat.exists

