---
- name: create wp database
  mysql_db:
   name: "{{ wp_dbname }}"
   state: present

- name: create wp database user (localhost)
  mysql_user:
   name: "{{ wp_dbuser }}"
   password: "{{ wp_dbpass }}"
   priv: "{{ wp_dbname }}.*:ALL,GRANT"
   host: localhost
   state: present

- name: create wp database user (all hosts)
  mysql_user:
   name: "{{ wp_dbuser }}"
   host_all: yes
   state: present

