---
- name: create a network
  os_network:
    name: "{{ network_name }}"
    cloud: "{{ target_cloud | default(omit) }}"
    state: present

- name: create a subnet
  os_subnet:
    name: "{{ subnet_name }}"
    network_name: "{{ network_name }}"
    cidr: "{{ subnet_cidr }}"
    dns_nameservers: "{{ dns_servers }}"
    cloud: "{{ target_cloud | default(omit) }}"
    state: present

- name: create a router
  os_router:
    name: "{{ router_name }}"
    network: "{{ router_attached_network }}"
    interfaces:
      - "{{ subnet_name }}"
    cloud: "{{ target_cloud | default(omit) }}"
    state: present

- name: register an public key as keypair
  os_keypair:
    name: "{{ keypair_name }}"
    cloud: "{{ target_cloud | default(omit) }}"
    public_key_file: "{{ keypair_public_key_file_path }}"
    state: present

